server:
  port: 8130
  servlet:
    context-path: /uaa

spring:
  application:
    name: scd-auth

#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 90  # 续约到期时间（默认90秒）
#    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔（默认30秒）
#  client:
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/

security:
  oauth2:
    authorization:
      check-token-access: permitAll()
      token-key-access: permitAll()
