server:
  port: 8110

spring:
  application:
    name: scd-admin
  boot:
    admin:
      ui:
        title: scd-admin

# eureka配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/









