server:
  port: 8090

#从本地文件读取配置
spring:
  application:
    name: scd-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

#远程git仓库
#spring:
#  application:
#    name: scd-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/sandra199311/scd
#          search-paths:respo
#          username:
#          password:
#        default-label: master

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90  # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔（默认30秒）
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/


